category_questions_data = {
    "Science": [
        
    ("What is the chemical symbol for water?", [("H2O", True), ("O2", False), ("CO2", False)]),
    ("What is the largest planet in our solar system?", [("Jupiter", True), ("Saturn", False), ("Earth", False)]),
    ("What is the chemical symbol for gold?", [("Au", True), ("Ag", False), ("Fe", False)]),
    ("Who is known as the father of modern physics?", [("Albert Einstein", True), ("Isaac Newton", False), ("Galileo Galilei", False)]),
    ("What is the chemical symbol for oxygen?", [("O", True), ("O2", False), ("Ox", False)]),
    ("What gas do plants absorb from the atmosphere?", [("Carbon Dioxide", True), ("Oxygen", False), ("Nitrogen", False)]),
    ("Which element has the chemical symbol He?", [("Helium", True), ("Hydrogen", False), ("Hafnium", False)]),
    ("What is the center of an atom called?", [("Nucleus", True), ("Electron", False), ("Proton", False)]),
    ("How many planets are there in our solar system?", [("8", True), ("9", False), ("7", False)]),
    ("Which planet is known as the Red Planet?", [("Mars", True), ("Venus", False), ("Jupiter", False)]),
    ("What is the chemical symbol for sodium?", [("Na", True), ("S", False), ("N", False)]),
    ("What is the heaviest naturally occurring element?", [("Uranium", True), ("Lead", False), ("Gold", False)]),
    ("What is the main element in the sun?", [("Hydrogen", True), ("Oxygen", False), ("Carbon", False)]),
    ("What is the chemical symbol for iron?", [("Fe", True), ("Ir", False), ("I", False)]),
    ("Which planet is closest to the sun?", [("Mercury", True), ("Venus", False), ("Earth", False)]),
    ("What is the hardest natural substance on Earth?", [("Diamond", True), ("Gold", False), ("Iron", False)]),
    ("What is the largest organ in the human body?", [("Skin", True), ("Liver", False), ("Heart", False)]),
    ("Who developed the theory of evolution?", [("Charles Darwin", True), ("Albert Einstein", False), ("Isaac Newton", False)]),
    ("What is the chemical symbol for potassium?", [("K", True), ("P", False), ("Na", False)]),
    ("What is the smallest planet in our solar system?", [("Mercury", True), ("Mars", False), ("Venus", False)]),
    ("What is the most common gas in Earth's atmosphere?", [("Nitrogen", True), ("Oxygen", False), ("Carbon Dioxide", False)]),
    ("What is the process by which plants make food?", [("Photosynthesis", True), ("Respiration", False), ("Digestion", False)]),
    ("Who is known as the father of modern chemistry?", [("Antoine Lavoisier", True), ("Dmitri Mendeleev", False), ("Marie Curie", False)]),
    ("What is the chemical symbol for chlorine?", [("Cl", True), ("C", False), ("Co", False)]),
    ("What is the freezing point of water in Celsius?", [("0°C", True), ("32°F", False), ("100°C", False)]),
    ("Which of these is a non-metal?", [("Oxygen", True), ("Iron", False), ("Copper", False)]),
    ("What is the chemical symbol for copper?", [("Cu", True), ("Co", False), ("C", False)]),
    ("Which part of the plant conducts photosynthesis?", [("Leaf", True), ("Root", False), ("Stem", False)]),
    ("What is the chemical symbol for silver?", [("Ag", True), ("Si", False), ("S", False)]),
    ("Which is the longest bone in the human body?", [("Femur", True), ("Humerus", False), ("Tibia", False)]),
    ("Which planet is known for its rings?", [("Saturn", True), ("Jupiter", False), ("Mars", False)]),
    ("What is the chemical symbol for zinc?", [("Zn", True), ("Z", False), ("Zc", False)]),
    ("Who discovered gravity?", [("Isaac Newton", True), ("Albert Einstein", False), ("Galileo Galilei", False)]),
    ("What is the chemical formula for methane?", [("CH4", True), ("CO2", False), ("C2H6", False)]),
    ("What is the chemical symbol for mercury?", [("Hg", True), ("Mn", False), ("Mg", False)]),
    ("What type of energy does a moving object have?", [("Kinetic energy", True), ("Potential energy", False), ("Thermal energy", False)]),
    ("What is the chemical formula for carbon dioxide?", [("CO2", True), ("C2H6", False), ("CO", False)]),
    ("What is the name of the galaxy we live in?", [("Milky Way", True), ("Andromeda", False), ("Sombrero", False)]),
    ("Which scientist proposed the heliocentric theory?", [("Nicolaus Copernicus", True), ("Galileo Galilei", False), ("Johannes Kepler", False)]),
    ("What is the chemical symbol for nitrogen?", [("N", True), ("Na", False), ("O", False)]),
    ("What is the boiling point of water in Fahrenheit?", [("212°F", True), ("100°C", False), ("32°F", False)]),
    ("Which planet has the most moons?", [("Jupiter", True), ("Saturn", False), ("Mars", False)]),
    ("What is the most abundant element in the Earth's crust?", [("Oxygen", True), ("Iron", False), ("Carbon", False)]),
    ("What is the chemical symbol for carbon?", [("C", True), ("Ca", False), ("Cr", False)]),
    ("Who invented the telephone?", [("Alexander Graham Bell", True), ("Thomas Edison", False), ("Nikola Tesla", False)]),
    ("What is the main gas responsible for climate change?", [("Carbon Dioxide", True), ("Oxygen", False), ("Nitrogen", False)]),
    ("What is the process by which animals break down food?", [("Digestion", True), ("Respiration", False), ("Excretion", False)]),
    ("Which planet is known as the Morning Star?", [("Venus", True), ("Mars", False), ("Mercury", False)]),
    ("What is the atomic number of hydrogen?", [("1", True), ("2", False), ("3", False)]),
    ("Which element is represented by the symbol 'K'?", [("Potassium", True), ("Krypton", False), ("Calcium", False)]),
    ("What is the primary source of energy for the Earth?", [("The Sun", True), ("The Moon", False), ("The Earth itself", False)]),
    ("What is the chemical formula for water?", [("H2O", True), ("H2O2", False), ("O2", False)]),
    ("What organ in the human body pumps blood?", [("Heart", True), ("Brain", False), ("Liver", False)]),
    ("Which gas is most commonly used in balloons?", [("Helium", True), ("Hydrogen", False), ("Oxygen", False)]),
    ("What is the chemical symbol for calcium?", [("Ca", True), ("C", False), ("Cl", False)]),
    ("Which type of rock is formed from cooling lava?", [("Igneous", True), ("Sedimentary", False), ("Metamorphic", False)]),
    ("What is the most abundant element in the universe?", [("Hydrogen", True), ("Helium", False), ("Carbon", False)]),
    ("What is the main function of red blood cells?", [("Transport oxygen", True), ("Fight infection", False), ("Clot blood", False)]),
    ("What is the chemical symbol for helium?", [("He", True), ("H", False), ("Li", False)]),
    ("What is the chemical formula for ammonia?", [("NH3", True), ("NH4", False), ("N2H4", False)]),
    ("What is the most common state of matter in the universe?", [("Plasma", True), ("Solid", False), ("Liquid", False)]),
    ("Who formulated the laws of motion?", [("Isaac Newton", True), ("Albert Einstein", False), ("Galileo Galilei", False)]),
    # Add more questions as needed

        # Add 195 more questions and answers for Science...
        
    ],
    "History": [
        
    ("Who was the first President of the United States?", [("George Washington", True), ("Thomas Jefferson", False), ("Abraham Lincoln", False)]),
    ("Which country was the first to land a man on the moon?", [("USA", True), ("Soviet Union", False), ("China", False)]),
    ("Who was the first emperor of China?", [("Qin Shi Huang", True), ("Emperor Wu", False), ("Genghis Khan", False)]),
    ("In which year did World War II end?", [("1945", True), ("1940", False), ("1950", False)]),
    ("Who was the first woman to fly solo across the Atlantic?", [("Amelia Earhart", True), ("Harriet Quimby", False), ("Bessie Coleman", False)]),
    ("What was the name of the ship that brought the Pilgrims to America in 1620?", [("Mayflower", True), ("Santa Maria", False), ("Titanic", False)]),
    ("Who was the longest-reigning British monarch before Queen Elizabeth II?", [("Queen Victoria", True), ("King George III", False), ("Queen Elizabeth I", False)]),
    ("Which ancient civilization built the pyramids of Giza?", [("Ancient Egyptians", True), ("Romans", False), ("Greeks", False)]),
    ("What year did the Berlin Wall fall?", [("1989", True), ("1979", False), ("1991", False)]),
    ("Which country was the first to grant women the right to vote?", [("New Zealand", True), ("United States", False), ("France", False)]),
    ("What ancient civilization is known for creating the first written laws?", [("Babylonians", True), ("Romans", False), ("Greeks", False)]),
    ("Which leader is known for his role in the Russian Revolution of 1917?", [("Vladimir Lenin", True), ("Joseph Stalin", False), ("Leon Trotsky", False)]),
    ("What was the name of the ship that sank on its maiden voyage in 1912?", [("Titanic", True), ("Lusitania", False), ("Queen Mary", False)]),
    ("Who was the first human to journey into outer space?", [("Yuri Gagarin", True), ("Neil Armstrong", False), ("Buzz Aldrin", False)]),
    ("Who was the leader of the Confederate States during the American Civil War?", [("Jefferson Davis", True), ("Abraham Lincoln", False), ("Robert E. Lee", False)]),
    ("What year did the United States declare its independence from Britain?", [("1776", True), ("1789", False), ("1812", False)]),
    ("Who was the leader of Nazi Germany during World War II?", [("Adolf Hitler", True), ("Joseph Stalin", False), ("Benito Mussolini", False)]),
    ("What ancient city was famously destroyed by an eruption of Mount Vesuvius in 79 AD?", [("Pompeii", True), ("Rome", False), ("Athens", False)]),
    ("Which country did the United States fight against in the Vietnam War?", [("North Vietnam", True), ("South Vietnam", False), ("China", False)]),
    ("Which ancient civilization built Machu Picchu?", [("Inca", True), ("Aztec", False), ("Maya", False)]),
    ("Which famous battle was fought on June 6, 1944, during World War II?", [("D-Day", True), ("Battle of the Bulge", False), ("Pearl Harbor", False)]),
    ("Who was the first emperor of Rome?", [("Augustus", True), ("Julius Caesar", False), ("Nero", False)]),
    ("In what year did Christopher Columbus first arrive in the Americas?", [("1492", True), ("1482", False), ("1500", False)]),
    ("What was the name of the first man-made satellite launched into space?", [("Sputnik 1", True), ("Apollo 11", False), ("Explorer 1", False)]),
    ("Who was the queen of England during the Spanish Armada in 1588?", [("Queen Elizabeth I", True), ("Queen Victoria", False), ("Mary I", False)]),
    ("What was the name of the ship that carried the first English settlers to Jamestown in 1607?", [("Susan Constant", True), ("Mayflower", False), ("Endeavour", False)]),
    ("In what year did World War I begin?", [("1914", True), ("1920", False), ("1939", False)]),
    ("Who was the first president of South Africa elected by universal suffrage?", [("Nelson Mandela", True), ("Desmond Tutu", False), ("F.W. de Klerk", False)]),
    ("Who invented the telephone?", [("Alexander Graham Bell", True), ("Thomas Edison", False), ("Nikola Tesla", False)]),
    ("Who was the British Prime Minister during most of World War II?", [("Winston Churchill", True), ("Neville Chamberlain", False), ("Clement Attlee", False)]),
    ("What year did the French Revolution begin?", [("1789", True), ("1776", False), ("1799", False)]),
    ("What was the name of the first artificial Earth satellite launched by the Soviet Union?", [("Sputnik 1", True), ("Vostok 1", False), ("Luna 1", False)]),
    ("Who was the first female pharaoh of ancient Egypt?", [("Sobekneferu", True), ("Cleopatra", False), ("Hatshepsut", False)]),
    ("Which empire was ruled by Genghis Khan?", [("Mongol Empire", True), ("Roman Empire", False), ("Ottoman Empire", False)]),
    ("In which year did the United States enter World War I?", [("1917", True), ("1914", False), ("1920", False)]),
    ("Who was the leader of the Indian independence movement?", [("Mahatma Gandhi", True), ("Jawaharlal Nehru", False), ("Subhas Chandra Bose", False)]),
    ("Which war was fought between the North and South regions of the United States?", [("American Civil War", True), ("War of 1812", False), ("Revolutionary War", False)]),
    ("What was the name of the first human-made object to reach the Moon?", [("Luna 2", True), ("Apollo 11", False), ("Sputnik 2", False)]),
    ("What was the name of the first human to walk on the moon?", [("Neil Armstrong", True), ("Yuri Gagarin", False), ("Buzz Aldrin", False)]),
    ("Which country was known as the Soviet Union?", [("Russia", True), ("Germany", False), ("China", False)]),
    ("Which English king had six wives?", [("Henry VIII", True), ("Richard III", False), ("Edward VI", False)]),
    ("Who was the first king of Israel?", [("Saul", True), ("David", False), ("Solomon", False)]),
    ("What was the name of the ship that brought the first English settlers to the New World?", [("Mayflower", True), ("Santa Maria", False), ("Endeavour", False)]),
    ("Which country was led by the dictator Benito Mussolini during World War II?", [("Italy", True), ("Germany", False), ("Spain", False)]),
    ("What was the name of the ship that brought the first English settlers to America in 1607?", [("Susan Constant", True), ("Mayflower", False), ("Titanic", False)]),
    ("In which year did the Great Fire of London occur?", [("1666", True), ("1612", False), ("1789", False)]),
    ("What ancient civilization built the Great Wall of China?", [("Ancient Chinese", True), ("Romans", False), ("Mongols", False)]),
    ("Which famous explorer is credited with discovering America in 1492?", [("Christopher Columbus", True), ("Vasco da Gama", False), ("Ferdinand Magellan", False)]),
    ("What war was fought between the United States and Mexico from 1846-1848?", [("Mexican-American War", True), ("War of 1812", False), ("Spanish-American War", False)]),
    ("Which country was once known as Persia?", [("Iran", True), ("Iraq", False), ("Afghanistan", False)]),
    ("Who was the first President of France?", [("Louis-Napoleon Bonaparte", True), ("Charles de Gaulle", False), ("Napoleon Bonaparte", False)]),
    # Add more questions as needed
        # Add 195 more questions and answers for History...
    ],
    "Geography": [
          ("What is the capital of France?", [("Paris", True), ("London", False), ("Berlin", False)]),
    ("Which country is the largest by area?", [("Russia", True), ("Canada", False), ("United States", False)]),
    ("Which continent is known as the 'Dark Continent'?", [("Africa", True), ("Asia", False), ("Australia", False)]),
    ("What is the longest river in the world?", [("Nile", True), ("Amazon", False), ("Yangtze", False)]),
    ("Which desert is the largest in the world?", [("Sahara", True), ("Gobi", False), ("Kalahari", False)]),
    ("What is the smallest country in the world?", [("Vatican City", True), ("Monaco", False), ("San Marino", False)]),
    ("Which ocean is the largest?", [("Pacific Ocean", True), ("Atlantic Ocean", False), ("Indian Ocean", False)]),
    ("Which mountain range is the longest in the world?", [("Andes", True), ("Himalayas", False), ("Rockies", False)]),
    ("What is the capital city of Japan?", [("Tokyo", True), ("Beijing", False), ("Seoul", False)]),
    ("Which country has the most official languages?", [("South Africa", True), ("India", False), ("Switzerland", False)]),
    ("Which river is the longest in North America?", [("Missouri River", True), ("Mississippi River", False), ("Colorado River", False)]),
    ("What is the capital of Canada?", [("Ottawa", True), ("Toronto", False), ("Vancouver", False)]),
    ("Which continent is the driest?", [("Antarctica", True), ("Africa", False), ("Australia", False)]),
    ("Which country has the most islands in the world?", [("Sweden", True), ("Canada", False), ("Philippines", False)]),
    ("What is the capital of Australia?", [("Canberra", True), ("Sydney", False), ("Melbourne", False)]),
    ("Which is the largest island in the world?", [("Greenland", True), ("New Guinea", False), ("Borneo", False)]),
    ("Which sea is the largest in the world?", [("Philippine Sea", True), ("Mediterranean Sea", False), ("Caribbean Sea", False)]),
    ("What is the capital of Brazil?", [("Brasília", True), ("Rio de Janeiro", False), ("São Paulo", False)]),
    ("Which country is home to the city of Machu Picchu?", [("Peru", True), ("Mexico", False), ("Ecuador", False)]),
    ("What is the smallest continent by land area?", [("Australia", True), ("Antarctica", False), ("Europe", False)]),
    ("Which country is the world's most populous?", [("China", True), ("India", False), ("United States", False)]),
    ("Which country has the most time zones?", [("Russia", True), ("United States", False), ("Canada", False)]),
    ("What is the highest mountain in the world?", [("Mount Everest", True), ("K2", False), ("Kangchenjunga", False)]),
    ("Which ocean is the smallest?", [("Arctic Ocean", True), ("Southern Ocean", False), ("Indian Ocean", False)]),
    ("Which country is both in Europe and Asia?", [("Turkey", True), ("Russia", False), ("Egypt", False)]),
    ("What is the capital of Italy?", [("Rome", True), ("Florence", False), ("Venice", False)]),
    ("Which African country has the largest population?", [("Nigeria", True), ("Ethiopia", False), ("Egypt", False)]),
    ("Which U.S. state is known as the 'Sunshine State'?", [("Florida", True), ("California", False), ("Hawaii", False)]),
    ("Which is the largest country in Africa by area?", [("Algeria", True), ("Sudan", False), ("Democratic Republic of the Congo", False)]),
    ("Which is the longest mountain range in North America?", [("Rocky Mountains", True), ("Appalachian Mountains", False), ("Sierra Nevada", False)]),
    ("Which country has the largest economy in Africa?", [("Nigeria", True), ("South Africa", False), ("Egypt", False)]),
    ("What is the largest country in South America?", [("Brazil", True), ("Argentina", False), ("Colombia", False)]),
    ("Which is the largest island in the Caribbean?", [("Cuba", True), ("Hispaniola", False), ("Jamaica", False)]),
    ("Which desert is located in northern China and southern Mongolia?", [("Gobi Desert", True), ("Kalahari Desert", False), ("Sonoran Desert", False)]),
    ("What is the capital of Egypt?", [("Cairo", True), ("Alexandria", False), ("Luxor", False)]),
    ("Which country is known as the 'Land of the Rising Sun'?", [("Japan", True), ("China", False), ("Thailand", False)]),
    ("Which is the longest river in South America?", [("Amazon River", True), ("Paraná River", False), ("Orinoco River", False)]),
    ("Which country is home to the ancient city of Petra?", [("Jordan", True), ("Lebanon", False), ("Syria", False)]),
    ("Which island nation is located off the southeastern coast of India?", [("Sri Lanka", True), ("Maldives", False), ("Mauritius", False)]),
    ("What is the capital of Spain?", [("Madrid", True), ("Barcelona", False), ("Seville", False)]),
    ("Which mountain is the tallest in North America?", [("Denali", True), ("Mount Rainier", False), ("Mount Whitney", False)]),
    ("What is the largest country in Europe?", [("Russia", True), ("France", False), ("Ukraine", False)]),
    ("Which U.S. state is the Grand Canyon located in?", [("Arizona", True), ("Utah", False), ("Nevada", False)]),
    ("Which country has the longest coastline in the world?", [("Canada", True), ("Australia", False), ("Russia", False)]),
    ("What is the capital of South Korea?", [("Seoul", True), ("Tokyo", False), ("Beijing", False)]),
    ("Which is the second largest country in the world?", [("Canada", True), ("United States", False), ("China", False)]),
    ("What is the name of the longest river in Europe?", [("Volga River", True), ("Danube River", False), ("Rhine River", False)]),
    ("Which U.S. state is known as the 'Empire State'?", [("New York", True), ("California", False), ("Texas", False)]),
    ("Which country is the largest in the Middle East?", [("Saudi Arabia", True), ("Iran", False), ("Iraq", False)]),
    ("Which country is the smallest in the European Union?", [("Malta", True), ("Luxembourg", False), ("Cyprus", False)]),
    ("Which country has the highest population density?", [("Monaco", True), ("Singapore", False), ("Hong Kong", False)]),
    ("What is the name of the famous mountain range in South America?", [("Andes", True), ("Himalayas", False), ("Rockies", False)]),
    ("Which city is the largest in the world by population?", [("Tokyo", True), ("New York", False), ("Shanghai", False)]),
    ("Which European country is known for tulips, windmills, and clogs?", [("Netherlands", True), ("Belgium", False), ("Germany", False)]),
    # Add more questions as needed
    ],
    "Art": [
        ("Who painted the Mona Lisa?", [("Leonardo da Vinci", True), ("Vincent van Gogh", False), ("Pablo Picasso", False)]),
        ("What is the art style used by Salvador Dalí?", [("Surrealism", True), ("Cubism", False), ("Impressionism", False)]),
        ("Which artist is known for the creation of the Sistine Chapel ceiling?", [("Michelangelo", True), ("Raphael", False), ("Leonardo da Vinci", False)]),
        ("What is the most famous sculpture created by Michelangelo?", [("David", True), ("The Thinker", False), ("Venus de Milo", False)]),
        ("Which famous art movement was Pablo Picasso a part of?", [("Cubism", True), ("Surrealism", False), ("Dadaism", False)]),
        # Add 195 more questions and answers for Art...
    ],
    "Sports": [
        ("Who won the FIFA World Cup in 2018?", [("France", True), ("Croatia", False), ("Brazil", False)]),
        ("How many players are on a standard soccer team?", [("11", True), ("10", False), ("12", False)]),
        ("Which country has won the most Olympic gold medals?", [("United States", True), ("Russia", False), ("China", False)]),
        ("Who holds the record for most goals in a single Premier League season?", [("Mohamed Salah", True), ("Harry Kane", False), ("Cristiano Ronaldo", False)]),
        ("What is the term for a score of zero in tennis?", [("Love", True), ("Nil", False), ("Zero", False)]),
        # Add 195 more questions and answers for Sports...
    ],
    # Add more categories like Technology, Music, Movies, etc.
}

