# Generated by Django 5.1.6 on 2025-02-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
