# Generated by Django 5.1.6 on 2025-02-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quizcategory_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('question', 'is_correct'), name='unique_correct_answer'),
        ),
    ]
