# Generated by Django 5.1.6 on 2025-02-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answer_unique_correct_answer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answer',
            name='unique_correct_answer',
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
